import {
  AppWindow,
  Bot,
  Boxes,
  Compass,
  Fingerprint,
  Gauge,
  Globe,
  LifeBuoy,
  ListChecks,
  MessageCircle,
  MessagesSquare,
  MousePointerClick,
  PenLine,
  Plug,
  Sparkles,
  Store,
  Workflow,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** Mapa de ícones referenciados por nome em content/site.ts */
export const iconMap: Record<string, LucideIcon> = {
  app: AppWindow,
  bot: Bot,
  boxes: Boxes,
  compass: Compass,
  fingerprint: Fingerprint,
  gauge: Gauge,
  globe: Globe,
  lifebuoy: LifeBuoy,
  list: ListChecks,
  message: MessageCircle,
  messages: MessagesSquare,
  pointer: MousePointerClick,
  pen: PenLine,
  plug: Plug,
  sparkles: Sparkles,
  store: Store,
  workflow: Workflow,
  zap: Zap,
};
